# Generated by Django 2.2.3 on 2020-02-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resort_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quad', 'Quad'), (' queen', ' Queen'), ('king', 'King'), ('twin', 'Twin'), (' hollywood twin room', ' Hollywood Twin Room'), ('double-double', 'Double-double'), ('studio', 'Studio'), ('suite / executive suite', 'Suite / Executive Suite'), ('mini suite or junior suite', 'Mini Suite or Junior Suite'), ('president suite / presidential suite', 'President Suite | Presidential Suite'), ('apartments / room for extended stay', 'Apartments / Room for Extended Stay'), ('connecting rooms', 'Connecting rooms'), ('murphy room', 'Murphy Room'), ('accessible room / disabled room', 'Accessible Room / Disabled Room'), ('cabana', 'Cabana'), ('adjoining rooms:', 'Adjoining rooms:'), ('adjacent rooms', 'Adjacent rooms'), ('villa', 'Villa'), ('floored room', 'Floored Room'), ('smoking / non-smoking Room', 'Smoking / Non-Smoking Room')], max_length=50)),
                ('room_image', models.ImageField(default='', upload_to='room_image')),
                ('room_details', models.TextField(default='', max_length=9000)),
                ('resort_name', models.CharField(default='Athletic_Resort', max_length=20)),
                ('price', models.CharField(default='', max_length=100)),
                ('capacity', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Resort Room',
            },
        ),
    ]
