# Generated by Django 2.2.3 on 2020-02-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0002_auto_20200208_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepad',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
